---
abstract: 'Triple DES in CBC mode'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  Test::Most: 0.22
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-TripleDES-CBC
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Crypt::TripleDES::CBC:
    file: lib/Crypt/TripleDES/CBC.pm
    version: 0.001
requires:
  Crypt::DES: 0
  Moose: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/crypt-tripledes-cbc/issues
  homepage: https://metacpan.org/release/Crypt-TripleDES-CBC
  repository: git://github.com/shantanubhadoria/crypt-tripledes-cbc.git
version: 0.001
x_contributors:
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
